name: HomeworkCI

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest
    env:
      PROJ_NAME: ${{ github.event.repository.name }}
      IMG_TAG: ${{ github.ref_name }}
      DOCKER_NAMESPACE: ${{ vars.DOCKER_NAMESPACE }}

    steps:

      - name: Set up Github Action Checkout
        uses: actions/checkout@v3
      
      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build Docker Image
        run: |
          echo building $PROJ_NAME:$IMG_TAG image
          docker build --tag $PROJ_NAME:$IMG_TAG .

      - name: Retagging Docker Image for Push
        run: |
          echo Retagging $PROJ_NAME:$IMG_TAG image
          docker tag $PROJ_NAME:$IMG_TAG $DOCKER_NAMESPACE/$PROJ_NAME:$IMG_TAG
          docker image ls
      
      - name: Pushing Docker Image
        run: |
          echo pushing $PROJ_NAME:$IMG_TAG image
          docker push $DOCKER_NAMESPACE/$PROJ_NAME:$IMG_TAG

      - name: Deleting local Docker Images
        run: |
          echo deleting local instance of $IMG_TAG image
          docker image remove $PROJ_NAME:$IMG_TAG
          docker image remove $DOCKER_NAMESPACE/$PROJ_NAME:$IMG_TAG
          docker image ls

      - name: Downloading CLI Client
        run: |
          echo "Downloading the CLI"
          curl "https://downloads.mend.io/cli/linux_amd64/mend" -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
     
      - name: Verify Scanner
        run: |
          echo "Verifying the CLI"
          mend version
      
      - name: Running CLI
        env: 
          MEND_URL: ${{ secrets.MEND_URL }}
          MEND_USER_KEY: ${{ secrets.MEND_USER_KEY }}
          MEND_EMAIL: ${{ secrets.MEND_EMAIL }}
          MEND_LOG_LEVEL: "DEBUG"
          
        run: |
          echo running CLI scan on $DOCKER_NAMESPACE/$PROJ_NAME:$IMG_TAG
          mend image $DOCKER_NAMESPACE/$PROJ_NAME:$IMG_TAG --scope "DockerHub//$PROJ_NAME" --non-interactive
        continue-on-error: true
