     # This is a basic workflow to help you get started with Actions

name: HomeworkCI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      PROJ_NAME: ${{ github.event.repository.name }}
      IMG_TAG: ${{ github.ref_name }}
      DOCKER_URL: ${{ vars.DOCKER_URL }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set up Github Action Checkout
        uses: actions/checkout@v3
      
      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build Docker Image
        run: |
          echo building $PROJ_NAME:$IMG_TAG image
          docker build --tag $PROJ_NAME:$IMG_TAG .

      - name: Pushing Docker Image
        run: |
          echo pushing $DOCKER_URL/$PROJ_NAME:$IMG_TAG image
          docker push $DOCKER_URL/$PROJ_NAME:$IMG_TAG

      - name: Deleting local Docker Image
        run: |
          echo deleting local instance of $IMG_TAG image
          docker image remove $PROJ_NAME:$IMG_TAG

      - name: Downloading CLI Client
        run: |
          echo "Downloading the CLI"
          curl "https://downloads.mend.io/cli/linux_amd64/mend" -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
     
      - name: Verify Scanner
        run: |
          echo "Verifying the CLI"
          mend version
      
      - name: Running CLI
        env: 
          MEND_URL: ${{ secrets.MEND_URL }}
          MEND_USER_KEY: ${{ secrets.MEND_USER_KEY }}
          MEND_EMAIL: ${{ secrets.MEND_EMAIL }}
          MEND_LOG_LEVEL: "DEBUG"
          
        run: |
          echo running CLI scan on $PROJ_NAME:$IMG_TAG
          mend image $DOCKER_URL/$PROJ_NAME:$IMG_TAG --scope "DockerHub//$PROJ_NAME" --non-interactive
        continue-on-error: true
        
      - name: Printing CLI logs
        run: |
         cat ~/.mend/logs/sca/*
